on: push

name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test (MSRV)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build

      - run: cargo test

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

  build-remote:
    name: Build and Test Remote Feature (MSRV)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build --features remote

      - run: cargo test --features remote

  build-standalone:
    name: Build and Test Standalone Feature (MSRV)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build --features standalone

      - run: cargo test --features standalone

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build development version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: httpmock/httpmock:build
